# Generated by Django 4.2.3 on 2023-07-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_delivery_address',
            field=models.BooleanField(default=False),
        ),
    ]
