# Generated by Django 4.2.3 on 2023-07-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gname',
            new_name='name',
        ),
    ]
