# Generated by Django 4.2.3 on 2023-07-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bannerimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
