# Generated by Django 4.2.3 on 2023-07-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bannerimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_image',
        ),
    ]
