# Generated by Django 4.2.3 on 2023-08-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
