# Generated by Django 4.2.3 on 2023-07-27 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_useraddress_is_delivery_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('SHIPPED', 'shipped'), ('ORDERED', 'ordered'), ('RETURN', 'return'), ('REFUND', 'refund')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('PREPAID', 'PREPAID'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('WALLET', 'wallet')], max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariant')),
            ],
        ),
    ]
