# Generated by Django 4.2.3 on 2023-08-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_status_order_shipping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
