# Generated by Django 4.2.3 on 2023-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancelled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_period_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
